export const GET_MY_ACCOUNT = 'GET_MY_ACCOUNT';
export const RECEIVE_MY_ACCOUNT = 'RECEIVE_MY_ACCOUNT';
export const GET_MOVEMENTS = 'GET_MOVEMENTS';
export const RECEIVE_MOVEMENTS = 'RECEIVE_MOVEMENTS';
